name: Upload coverage to codecov.io
on:
  workflow_call:
    inputs:
      artifact:
        description: 'Name of the coverage artifact.'
        type: string
        required: false
        default: 'coverage'
jobs:
  upload:
    name: Upload coverage to codecov.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: target/coverage
      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          directory: target/coverage
          fail_ci_if_error: true
          verbose: true
